version: "3.9"

services:
  api:
    build: .
    container_name: healthcare-api

    ports:
      - "5050:5000"

    depends_on:
      - redis

    environment:
      PORT: 5000
      MONGO_URI: ${MONGO_URI}
      REDIS_URL: ${REDIS_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_EXPIRES_IN: 7d
      JWT_REFRESH_EXPIRES_IN: 30d
      CLIENT_URL: ${CLIENT_URL}
      LOG_LEVEL: info

    volumes:
      - .:/app
      - /app/node_modules

  redis:
    image: redis:7
    container_name: healthcare-redis

    ports:
      - "6379:6379"